name: inventory_plus
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_splash_screen: ^1.3.0
  flex_color_scheme: ^5.0.1
  flutter_barcode_scanner: ^2.0.0
  flutter_colorpicker: ^1.0.3
  flutter_image_slideshow: ^0.1.2
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  http: ^0.13.4
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  page_transition: ^2.0.9
  path: ^1.8.1
  provider: ^6.0.3
  url_launcher: ^6.1.5


dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
